// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "hyunchul"
#define SECRET_PASS "sshsshhc"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a1pmxpecyybpl-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICiDCCAXCgAwIBAgIUfrAu2FWUwzA8XxgcyONnCuUZ4Z0wDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIwMTEwODA5Mjgz
N1oXDTQ5MTIzMTIzNTk1OVowGDEWMBQGA1UEAxMNTXlNS1JXaUZpMTAxMDBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABIWWAOydqp/kLzvwnEbQSbHReM8moLobcGXn
ygkTeqPboIWgY443C4qO3r1+j8hgat74eSjiR5j1ylf7MtyAfUijYDBeMB8GA1Ud
IwQYMBaAFPX/DmvFLIpXMU9f8SWxHuRoX19HMB0GA1UdDgQWBBQ7HKTU4kwMXcH0
IwwfjwLj0qV2PTAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG
9w0BAQsFAAOCAQEAK7Ho43ukkPxHIWok2w7IxOo6bIQwoCyc5f82yk3hKo+PhEeK
Q/uv4GN5OpV67S5S7U64Gz1WfVHJ+QHvZJgDzqsZQKrnk0vx8MeV1gQ8oIJXxr1i
n2bhzhCR2vU7Q3vcj4/A5YFwBAQVutz8epXejm6Xfrju4Jzaiu3Bv5JZ22FXqKDC
drIO5hNWxqyLsVzUlVriwqNmNSmPr2+cO8hVGM6sTQGAvL9z4e90F9k/c8Xd1ks9
H25XYfVKi1t1ATXlCrBbQqneih0R5jQPHKQMYoPLMRaNCXfhHeMnQZbnujcO5Lx3
UlT63oW7OR8scsn3vOm2QB50ZOBTKAaKK2raeQ==
-----END CERTIFICATE-----
)";
